global:
  scrape_interval: 10s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
  - job_name: krakend-api-gateway
    static_configs:
      - targets:
          - kraend-api-gateway:9090